In [1]:
import pandas as pd

In [4]:
data = {
    '학번': ['2024001', '2024002', '2024003', '2024004', '2024005',
             '2024006', '2024007', '2024008', '2024009', '2024010'],
    '이름': ['김민준', '이서연', '박지호', '최수아', '정우진',
             '강하은', '윤도현', '임지유', '한준서', '오서현'],
    '학과': ['컴퓨터공학', '정보통신', '컴퓨터공학', '소프트웨어', '정보통신',
             '컴퓨터공학', '소프트웨어', '정보통신', '컴퓨터공학', '소프트웨어'],
    '학년': [1, 2, 1, 3, 2, 1, 3, 2, 1, 3],
    '파이썬점수': [85, 92, 78, 95, 88, 73, 90, 82, 76, 94],
    '자바점수': [90, 85, 82, 88, 92, 70, 95, 78, 80, 87],
    '출석률': [95.0, 98.0, 85.0, 100.0, 90.0, 78.0, 92.0, 88.0, 82.0, 96.0]
}

df = pd.DataFrame(data)
df

        학번   이름     학과  학년  파이썬점수  자바점수    출석률
0  2024001  김민준  컴퓨터공학   1     85    90   95.0
1  2024002  이서연   정보통신   2     92    85   98.0
2  2024003  박지호  컴퓨터공학   1     78    82   85.0
3  2024004  최수아  소프트웨어   3     95    88  100.0
4  2024005  정우진   정보통신   2     88    92   90.0
5  2024006  강하은  컴퓨터공학   1     73    70   78.0
6  2024007  윤도현  소프트웨어   3     90    95   92.0
7  2024008  임지유   정보통신   2     82    78   88.0
8  2024009  한준서  컴퓨터공학   1     76    80   82.0
9  2024010  오서현  소프트웨어   3     94    87   96.0

In [ ]:
#데이터의 기본 정보 확인

#5개의 데이터셋을 확인
df.head()
df.head(3) #3개의 데이터셋을 확인

df.shape #행과 열 갯수 파악

df.info() #컬럼명, 컬럼의 자료형, null데이터 여부 확인

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   학번      10 non-null     str
 1   이름      10 non-null     str
 2   학과      10 non-null     str
 3   학년      10 non-null     int64
 4   파이썬점수   10 non-null     int64
 5   자바점수    10 non-null     int64
 6   출석률     10 non-null     float64
dtypes: float64(1), int64(3), str(3)
memory usage: 692.0 bytes

In [12]:
#edu_users.csv 파일 로드
edu_df = pd.read_csv('edu_users.csv')
edu_df

,rate_math,rate_science,rate_english,rate_humanities,rate_art,tot_time,device,gender,age,resub_yn,comb_yn,othersub_yn,leave_yn
0,0.375,0.797,0.828,0.896,0.394,17.09,mobile,M,30,N,N,Y,1
1,0.951,0.482,0.765,0.909,0.473,28.57,tablet,F,25,N,Y,N,1
2,0.732,0.117,0.574,0.314,0.855,40.97,tablet,F,24,N,N,N,0
3,0.599,0.125,0.956,0.691,0.340,8.09,mobile,M,14,Y,N,N,1
4,0.156,0.686,0.200,0.272,0.870,45.34,tablet,F,15,Y,N,N,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1245,0.626,0.492,0.212,0.897,0.607,16.80,pc,M,24,Y,N,Y,0
1246,0.131,0.577,0.664,0.119,0.167,33.37,tablet,F,40,N,N,N,0
1247,0.033,0.866,0.411,0.328,0.797,27.37,mobile,M,23,N,N,N,0
1248,0.921,0.981,0.402,0.816,0.720,NaN,pc,F,23,Y,N,Y,0
1249,0.617,0.408,0.885,0.597,0.086,17.90,pc,M,15,N,N,N,0

In [ ]:
#null 데이터 확인(각 컬럼의 null 데이터 갯수 확인)
edu_df.isnull().sum()

rate_math          62
rate_science       62
rate_english        0
rate_humanities     0
rate_art            0
tot_time           62
device              0
gender              0
age                 0
resub_yn            0
comb_yn             0
othersub_yn         0
leave_yn            0
dtype: int64

In [20]:
#단일 컬럼의 정보만 출력
df['학과']

#여러 컬럼 선택
#ex> 이름, 학과 정보만 선택
df[['이름', '학과']]

    이름     학과
0  김민준  컴퓨터공학
1  이서연   정보통신
2  박지호  컴퓨터공학
3  최수아  소프트웨어
4  정우진   정보통신
5  강하은  컴퓨터공학
6  윤도현  소프트웨어
7  임지유   정보통신
8  한준서  컴퓨터공학
9  오서현  소프트웨어

In [27]:
#조건 필터링

#단일 조건 필터링
#ex> 파이썬 점수가 90점 이상인 학생 정보
df['파이썬점수'] >= 90 #각 행 데이터가 조건에 부합하는지 boolean타입 결과를 반환

#정답 코드
df[df['파이썬점수'] >= 90]

#ex> 학과가 '컴퓨터공학'인 학생 정보 조회
df[df['학과'] == '컴퓨터공학']

        학번   이름     학과  학년  파이썬점수  자바점수   출석률
0  2024001  김민준  컴퓨터공학   1     85    90  95.0
2  2024003  박지호  컴퓨터공학   1     78    82  85.0
5  2024006  강하은  컴퓨터공학   1     73    70  78.0
8  2024009  한준서  컴퓨터공학   1     76    80  82.0

In [ ]:
#다중 조건 필터링(and : &, or : |)
#ex> 파이썬 점수가 80점 이상이면서 학과가 '컴퓨터공학'인 학생 정보 조회

#조건1
df['파이썬점수']>=80
df['학과']=='컴퓨터공학'

#정답코드
df[(df['파이썬점수']>=80) & (df['학과']=='컴퓨터공학')]

        학번   이름     학과  학년  파이썬점수  자바점수   출석률
0  2024001  김민준  컴퓨터공학   1     85    90  95.0

In [37]:
#여러 값 중 하나의 값에 해당하는 데이터 조회
#ex>학과가 '컴퓨터공학'이거나 '소프트웨어'인 학생 정보 조회

#다중 조건을 이용한 풀이
df[(df['학과'] == '컴퓨터공학') | (df['학과'] == '소프트웨어')]

#isin() 함수를 이용한 출력
df[df['학과'].isin(['컴퓨터공학', '소프트웨어'])]

        학번   이름     학과  학년  파이썬점수  자바점수    출석률
0  2024001  김민준  컴퓨터공학   1     85    90   95.0
2  2024003  박지호  컴퓨터공학   1     78    82   85.0
3  2024004  최수아  소프트웨어   3     95    88  100.0
5  2024006  강하은  컴퓨터공학   1     73    70   78.0
6  2024007  윤도현  소프트웨어   3     90    95   92.0
8  2024009  한준서  컴퓨터공학   1     76    80   82.0
9  2024010  오서현  소프트웨어   3     94    87   96.0

In [39]:
#조건에 맞는 특정 컬럼 데이터만 조회
#파이썬 점수가 90점 이상인 학생들의 이름, 학과, 파이썬 점수를 조회
# df[조건][컬럼명]
df[(df['파이썬점수']>=90)][['이름','학과','파이썬점수']]

    이름     학과  파이썬점수
1  이서연   정보통신     92
3  최수아  소프트웨어     95
6  윤도현  소프트웨어     90
9  오서현  소프트웨어     94

In [48]:
#1. 이름, 출석률 커럼 데이터 조회
df[['이름', '출석률']]
#2. 출석률이 90이상인 학생 정보를 조회
df[df['출석률'] >= 90]
#3. 학년이 2학년이면서 자바 점수가 80점 이상인 학생의 이름, 학년, 자바점수를 조회
df[(df['학년']==2) & (df['자바점수']>=80)][['이름','학년','자바점수']]
#4. 학과가 '정보통신' 혹은 '소프트웨어'인 학생 정보 출력
df[df['학과'].isin(['정보통신', '소프트웨어'])]

        학번   이름     학과  학년  파이썬점수  자바점수    출석률
1  2024002  이서연   정보통신   2     92    85   98.0
3  2024004  최수아  소프트웨어   3     95    88  100.0
4  2024005  정우진   정보통신   2     88    92   90.0
6  2024007  윤도현  소프트웨어   3     90    95   92.0
7  2024008  임지유   정보통신   2     82    78   88.0
9  2024010  오서현  소프트웨어   3     94    87   96.0