In [1]:
import pandas as pd

In [3]:
data = {
    '학번': ['2024001', '2024002', '2024003', '2024004', '2024005',
             '2024006', '2024007', '2024008', '2024009', '2024010'],
    '이름': ['김민준', '이서연', '박지호', '최수아', '정우진',
             '강하은', '윤도현', '임지유', '한준서', '오서현'],
    '학과': ['컴퓨터공학', '정보통신', '컴퓨터공학', '소프트웨어', '정보통신',
             '컴퓨터공학', '소프트웨어', '정보통신', '컴퓨터공학', '소프트웨어'],
    '학년': [1, 2, 1, 3, 2, 1, 3, 2, 1, 3],
    '파이썬점수': [85, 92, 78, 95, 88, 73, 90, 82, 76, 94],
    '자바점수': [90, 85, 82, 88, 92, 70, 95, 78, 80, 87],
    '출석률': [95.0, 98.0, 85.0, 100.0, 90.0, 78.0, 92.0, 88.0, 82.0, 96.0]
}

df = pd.DataFrame(data)
df

        학번   이름     학과  학년  파이썬점수  자바점수    출석률
0  2024001  김민준  컴퓨터공학   1     85    90   95.0
1  2024002  이서연   정보통신   2     92    85   98.0
2  2024003  박지호  컴퓨터공학   1     78    82   85.0
3  2024004  최수아  소프트웨어   3     95    88  100.0
4  2024005  정우진   정보통신   2     88    92   90.0
5  2024006  강하은  컴퓨터공학   1     73    70   78.0
6  2024007  윤도현  소프트웨어   3     90    95   92.0
7  2024008  임지유   정보통신   2     82    78   88.0
8  2024009  한준서  컴퓨터공학   1     76    80   82.0
9  2024010  오서현  소프트웨어   3     94    87   96.0

In [4]:
# 새 컬럼 및 데이터 추가
#ex> '총점수' 컬럼 생성 및 총점 데이터 추가
df['총점수'] = df['파이썬점수'] + df['자바점수']
df

        학번   이름     학과  학년  파이썬점수  자바점수    출석률  총점수
0  2024001  김민준  컴퓨터공학   1     85    90   95.0  175
1  2024002  이서연   정보통신   2     92    85   98.0  177
2  2024003  박지호  컴퓨터공학   1     78    82   85.0  160
3  2024004  최수아  소프트웨어   3     95    88  100.0  183
4  2024005  정우진   정보통신   2     88    92   90.0  180
5  2024006  강하은  컴퓨터공학   1     73    70   78.0  143
6  2024007  윤도현  소프트웨어   3     90    95   92.0  185
7  2024008  임지유   정보통신   2     82    78   88.0  160
8  2024009  한준서  컴퓨터공학   1     76    80   82.0  156
9  2024010  오서현  소프트웨어   3     94    87   96.0  181

In [ ]:
#출석률을 소수점 비율로 변경 (95.0 -> 0.95)
df['출석률'] = df['출석률'] / 100
df

        학번   이름     학과  학년  파이썬점수  자바점수   출석률  총점수
0  2024001  김민준  컴퓨터공학   1     85    90  0.95  175
1  2024002  이서연   정보통신   2     92    85  0.98  177
2  2024003  박지호  컴퓨터공학   1     78    82  0.85  160
3  2024004  최수아  소프트웨어   3     95    88  1.00  183
4  2024005  정우진   정보통신   2     88    92  0.90  180
5  2024006  강하은  컴퓨터공학   1     73    70  0.78  143
6  2024007  윤도현  소프트웨어   3     90    95  0.92  185
7  2024008  임지유   정보통신   2     82    78  0.88  160
8  2024009  한준서  컴퓨터공학   1     76    80  0.82  156
9  2024010  오서현  소프트웨어   3     94    87  0.96  181

In [10]:
#조건에 맞는 데이터 변경(파이썬 점수에 따른 등급 정보)
#1. 등급 컬럼 생성
df['등급']='C'
df

#2. '파이썬점수'가 90점 이상이면 등급을 'A'로 변경
#mask(조건, 변경할 값)
df['등급'] = df['등급'].mask(df['파이썬점수']>=90,'A')
df

#3. '파이썬점수가' 가 80~89점이면 등급을 'B'로 변경
df['등급'] = df['등급'].mask((df['파이썬점수']<=89) & (df['파이썬점수']>=80),'B')
df

        학번   이름     학과  학년  파이썬점수  자바점수   출석률  총점수 등급
0  2024001  김민준  컴퓨터공학   1     85    90  0.95  175  B
1  2024002  이서연   정보통신   2     92    85  0.98  177  A
2  2024003  박지호  컴퓨터공학   1     78    82  0.85  160  C
3  2024004  최수아  소프트웨어   3     95    88  1.00  183  A
4  2024005  정우진   정보통신   2     88    92  0.90  180  B
5  2024006  강하은  컴퓨터공학   1     73    70  0.78  143  C
6  2024007  윤도현  소프트웨어   3     90    95  0.92  185  A
7  2024008  임지유   정보통신   2     82    78  0.88  160  B
8  2024009  한준서  컴퓨터공학   1     76    80  0.82  156  C
9  2024010  오서현  소프트웨어   3     94    87  0.96  181  A

In [12]:
#값 치환
#ex> 정보통신 -> IT, 소프트웨어 -> SW
#replace('A', 'B') -> 'A'값을 'B'로 변경
#replace({'A' : 'B', 'C' : 'D'}) -> 'A'를 'B'로, 'C'를 'D'로
df['학과'] = df['학과'].replace({'정보통신' : 'IT', '소프트웨어' : 'SW'})
df

        학번   이름     학과  학년  파이썬점수  자바점수   출석률  총점수 등급
0  2024001  김민준  컴퓨터공학   1     85    90  0.95  175  B
1  2024002  이서연     IT   2     92    85  0.98  177  A
2  2024003  박지호  컴퓨터공학   1     78    82  0.85  160  C
3  2024004  최수아     SW   3     95    88  1.00  183  A
4  2024005  정우진     IT   2     88    92  0.90  180  B
5  2024006  강하은  컴퓨터공학   1     73    70  0.78  143  C
6  2024007  윤도현     SW   3     90    95  0.92  185  A
7  2024008  임지유     IT   2     82    78  0.88  160  B
8  2024009  한준서  컴퓨터공학   1     76    80  0.82  156  C
9  2024010  오서현     SW   3     94    87  0.96  181  A

In [13]:
#컬럼명 변경
#파이썬점수 -> python, 자바점수 -> java
df = df.rename(columns={'파이썬점수' : 'python', '자바점수' : 'java'})
df

        학번   이름     학과  학년  python  java   출석률  총점수 등급
0  2024001  김민준  컴퓨터공학   1      85    90  0.95  175  B
1  2024002  이서연     IT   2      92    85  0.98  177  A
2  2024003  박지호  컴퓨터공학   1      78    82  0.85  160  C
3  2024004  최수아     SW   3      95    88  1.00  183  A
4  2024005  정우진     IT   2      88    92  0.90  180  B
5  2024006  강하은  컴퓨터공학   1      73    70  0.78  143  C
6  2024007  윤도현     SW   3      90    95  0.92  185  A
7  2024008  임지유     IT   2      82    78  0.88  160  B
8  2024009  한준서  컴퓨터공학   1      76    80  0.82  156  C
9  2024010  오서현     SW   3      94    87  0.96  181  A

In [ ]:
# ------------------------- 실습 ----------------------------#

In [ ]:
#1. 평균점수 컬럼 생성, 해당 컬럼에는 파이썬과 자바점수의 평균값을 저장(소수점 둘째자리)
#소수점 : round()
df['평균'] = round((df['python']+df['java'])/2, 2)
df

        학번   이름     학과  학년  python  java   출석률  총점수 등급    평균 pass-yn
0  2024001  김민준  컴퓨터공학   1      85    90  0.95  175  B  87.5      합격
1  2024002  이서연     IT   2      92    85  0.98  177  A  88.5      합격
2  2024003  박지호  컴퓨터공학   1      78    82  0.85  160  C  80.0      합격
3  2024004  최수아     SW   3      95    88  1.00  183  A  91.5      합격
4  2024005  정우진     IT   2      88    92  0.90  180  B  90.0      합격
5  2024006  강하은  컴퓨터공학   1      73    70  0.78  143  C  71.5     불합격
6  2024007  윤도현     SW   3      90    95  0.92  185  A  92.5      합격
7  2024008  임지유     IT   2      82    78  0.88  160  B  80.0      합격
8  2024009  한준서  컴퓨터공학   1      76    80  0.82  156  C  78.0     불합격
9  2024010  오서현     SW   3      94    87  0.96  181  A  90.5      합격

In [ ]:
#2. '합격여부' 컬럼 생성, 평균 점수가 80점 이상이면 '합격', 미만이면 '불합격'
df['합격여부'] = '합격'
df

df['합격여부'] = df['합격여부'].mask(df['평균'] >= 80, '합격')
df
df['합격여부'] = df['합격여부'].mask(df['평균'] < 80, '불합격')
df

        학번   이름     학과  학년  python  java   출석률  총점수 등급    평균 합격여부
0  2024001  김민준  컴퓨터공학   1      85    90  0.95  175  B  87.5   합격
1  2024002  이서연     IT   2      92    85  0.98  177  A  88.5   합격
2  2024003  박지호  컴퓨터공학   1      78    82  0.85  160  C  80.0   합격
3  2024004  최수아     SW   3      95    88  1.00  183  A  91.5   합격
4  2024005  정우진     IT   2      88    92  0.90  180  B  90.0   합격
5  2024006  강하은  컴퓨터공학   1      73    70  0.78  143  C  71.5  불합격
6  2024007  윤도현     SW   3      90    95  0.92  185  A  92.5   합격
7  2024008  임지유     IT   2      82    78  0.88  160  B  80.0   합격
8  2024009  한준서  컴퓨터공학   1      76    80  0.82  156  C  78.0  불합격
9  2024010  오서현     SW   3      94    87  0.96  181  A  90.5   합격

In [27]:
#3. '합격여부' 컬럼명을 'pass-yn'으로 변경
df = df.rename(columns={'합격여부':'pass-yn'})
df

        학번   이름     학과  학년  python  java   출석률  총점수 등급    평균 pass-yn
0  2024001  김민준  컴퓨터공학   1      85    90  0.95  175  B  87.5      합격
1  2024002  이서연     IT   2      92    85  0.98  177  A  88.5      합격
2  2024003  박지호  컴퓨터공학   1      78    82  0.85  160  C  80.0      합격
3  2024004  최수아     SW   3      95    88  1.00  183  A  91.5      합격
4  2024005  정우진     IT   2      88    92  0.90  180  B  90.0      합격
5  2024006  강하은  컴퓨터공학   1      73    70  0.78  143  C  71.5     불합격
6  2024007  윤도현     SW   3      90    95  0.92  185  A  92.5      합격
7  2024008  임지유     IT   2      82    78  0.88  160  B  80.0      합격
8  2024009  한준서  컴퓨터공학   1      76    80  0.82  156  C  78.0     불합격
9  2024010  오서현     SW   3      94    87  0.96  181  A  90.5      합격

In [29]:
round(10.5)

10