In [1]:
import pandas as pd

In [2]:
data = {
    '학번': ['2024001', '2024002', '2024003', '2024004', '2024005',
             '2024006', '2024007', '2024008', '2024009', '2024010'],
    '이름': ['김민준', '이서연', '박지호', '최수아', '정우진',
             '강하은', '윤도현', '임지유', '한준서', '오서현'],
    '학과': ['컴퓨터공학', '정보통신', '컴퓨터공학', '소프트웨어', '정보통신',
             '컴퓨터공학', '소프트웨어', '정보통신', '컴퓨터공학', '소프트웨어'],
    '학년': [1, 2, 1, 3, 2, 1, 3, 2, 1, 3],
    '파이썬점수': [85, 92, 78, 95, 88, 73, 90, 82, 76, 94],
    '자바점수': [90, 85, 82, 88, 92, 70, 95, 78, 80, 87],
    '출석률': [95.0, 98.0, 85.0, 100.0, 90.0, 78.0, 92.0, 88.0, 82.0, 96.0]
}

df = pd.DataFrame(data)
df

        학번   이름     학과  학년  파이썬점수  자바점수    출석률
0  2024001  김민준  컴퓨터공학   1     85    90   95.0
1  2024002  이서연   정보통신   2     92    85   98.0
2  2024003  박지호  컴퓨터공학   1     78    82   85.0
3  2024004  최수아  소프트웨어   3     95    88  100.0
4  2024005  정우진   정보통신   2     88    92   90.0
5  2024006  강하은  컴퓨터공학   1     73    70   78.0
6  2024007  윤도현  소프트웨어   3     90    95   92.0
7  2024008  임지유   정보통신   2     82    78   88.0
8  2024009  한준서  컴퓨터공학   1     76    80   82.0
9  2024010  오서현  소프트웨어   3     94    87   96.0

In [3]:
#집계함수
#df.groupby(그룹화할 기준 컬럼)[결과컬럼].집계데이터
#집계데이터 : mean(), max(), min(), count(), median()

#학과별 파이썬점수의 평균
df.groupby('학과')['파이썬점수'].mean()

학과
소프트웨어    93.000000
정보통신     87.333333
컴퓨터공학    78.000000
Name: 파이썬점수, dtype: float64

In [4]:
#학과별 학생수
df.groupby('학과')['학번'].count()

학과
소프트웨어    3
정보통신     3
컴퓨터공학    4
Name: 학번, dtype: int64

In [15]:
#여러 기준으로 그룹핑
#학과 및 학년으로 그룹핑후 파이썬점수의 평균을 조회
df.groupby(['학과', '학년'])['파이썬점수'].mean()

학과     자바점수
소프트웨어  87      94.0
       88      95.0
       95      90.0
정보통신   78      82.0
       85      92.0
       92      88.0
컴퓨터공학  70      73.0
       80      76.0
       82      78.0
       90      85.0
Name: 파이썬점수, dtype: float64

In [18]:
#여러 집계 데이터 함께 조회
#학년별 파이썬 점수의 평균, 최대, 최소 점수를 조회
df.groupby('학년')['파이썬점수'].agg(['mean','max','min'])

         mean  max  min
학년
1   78.000000   85   73
2   87.333333   92   82
3   93.000000   95   90

In [34]:
#학과별로 파이썬점수와 자바점수의 평균
df.groupby('학년')[['파이썬점수', '자바점수']].mean()

        파이썬점수  자바점수
학년
1   78.000000  80.5
2   87.333333  85.0
3   93.000000  90.0

In [25]:
#1. 학과별 평균 출석률 조회
df.groupby('학과')['출석률'].mean()

학과
소프트웨어    96.0
정보통신     92.0
컴퓨터공학    85.0
Name: 출석률, dtype: float64

In [27]:
#2. 학년별 파이썬과 자바 점수의 최고점, 최저점을 조회
df.groupby('학년')[['파이썬점수', '자바점수']].agg(['max','min'])

   파이썬점수     자바점수
     max min  max min
학년
1     85  73   90  70
2     92  82   92  78
3     95  90   95  87

In [ ]:
#3. 학과별 학생수를 조회, 조회된 데이터를 'group_result.xlsx' 파일로 저장
# 원래 그룹화한 기준컬럼이 index가 됨
df.groupby('학과')['학번'].count().reset_index().to_excel('group_result.xlsx', index=False)

#reset_index() = index를 컬럼으로 변경

In [38]:
new_df = pd.read_excel('group_result.xlsx')
new_df

      학과  학번
0  소프트웨어   3
1   정보통신   3
2  컴퓨터공학   4

In [42]:
#정렬
#df.sort_values(정렬기준컬럼, ascending = True)

#파이썬 점수 기준 내림차순 정렬
df.sort_values('파이썬점수', ascending=False)

#먼저 학과 기준 오름차순 정렬 후 자바 점수 기준 내림차순 정렬
df.sort_values(['학과', '자바점수'], ascending=[True, False])

#정렬 후 index를 재 정렬
#reset_index() : 인덱스를 컬럼으로 변경 + 새로운 인덱스 부여
#reset_index(drop = True) : 기존의 인덱스는 버리고 새로운 인덱스를 부여
df.sort_values(['학과', '자바점수'], ascending=[True, False]).reset_index(drop=True)

        학번   이름     학과  학년  파이썬점수  자바점수    출석률
0  2024007  윤도현  소프트웨어   3     90    95   92.0
1  2024004  최수아  소프트웨어   3     95    88  100.0
2  2024010  오서현  소프트웨어   3     94    87   96.0
3  2024005  정우진   정보통신   2     88    92   90.0
4  2024002  이서연   정보통신   2     92    85   98.0
5  2024008  임지유   정보통신   2     82    78   88.0
6  2024001  김민준  컴퓨터공학   1     85    90   95.0
7  2024003  박지호  컴퓨터공학   1     78    82   85.0
8  2024009  한준서  컴퓨터공학   1     76    80   82.0
9  2024006  강하은  컴퓨터공학   1     73    70   78.0

In [64]:
#1. 출석률이 높은 순으로 데이터를 정렬 후, 상위 3명의 이름과 출석률 조회
df.sort_values('출석률', ascending=False)[['이름', '출석률']].reset_index(drop=True).head(3)

    이름    출석률
0  최수아  100.0
1  이서연   98.0
2  오서현   96.0

In [54]:
#2. df에서 학과기준 오름차순 정렬 후 자바 점수기준 내림차순 정렬
df.sort_values(['학과', '자바점수'],ascending=[True, False])

        학번   이름     학과  학년  파이썬점수  자바점수    출석률
6  2024007  윤도현  소프트웨어   3     90    95   92.0
3  2024004  최수아  소프트웨어   3     95    88  100.0
9  2024010  오서현  소프트웨어   3     94    87   96.0
4  2024005  정우진   정보통신   2     88    92   90.0
1  2024002  이서연   정보통신   2     92    85   98.0
7  2024008  임지유   정보통신   2     82    78   88.0
0  2024001  김민준  컴퓨터공학   1     85    90   95.0
2  2024003  박지호  컴퓨터공학   1     78    82   85.0
8  2024009  한준서  컴퓨터공학   1     76    80   82.0
5  2024006  강하은  컴퓨터공학   1     73    70   78.0

In [69]:
#3. 파이썬과 자바점수의 평균점수를 기준으로, 평점 점수 상위 5명의 데이터를 'top5.xlsx'파일로 저장

# 1) '평균'컬럼 생성 후 해당 컬럼에 자바와 파이썬 점수의 평균 데이터 저장(소숫점 첫째 자리)
df['평균'] = round((df['파이썬점수'] + df['자바점수'])/2, 1)
df
# 2) 평균점수 기준 내림차순 정렬 후 상위 5개의 데이터를 액셀로 저장
df.sort_values('평균', ascending=False).head(5).to_excel('top5.xlsx', index=False)

pd.read_excel('top5.xlsx')

        학번   이름     학과  학년  파이썬점수  자바점수  출석률    평균
0  2024007  윤도현  소프트웨어   3     90    95   92  92.5
1  2024004  최수아  소프트웨어   3     95    88  100  91.5
2  2024010  오서현  소프트웨어   3     94    87   96  90.5
3  2024005  정우진   정보통신   2     88    92   90  90.0
4  2024002  이서연   정보통신   2     92    85   98  88.5