# 데이터 분석(pandas) 평가 문제

---
- 코드 작성 전 아래 셀을 먼저 실행하여 pandas 라이브러리를 import 하세요.
- 데이터 파일 : **book_orders.xlsx**
---

In [2]:
# 코드 작성 전 이 셀을 실행하여 pandas 라이브러리를 import 하세요.
import pandas as pd

---
### 문제 1.
공유폴더에 제공한 **'book_orders.xlsx'** 파일을 불러와 DataFrame 데이터를 **'df'** 로 생성하고 출력하세요.

In [3]:
# 문제 1번 풀이 작성
df = pd.read_excel('book_orders.xlsx')

df

    주문번호  고객명  도서분류 출판사  지역     판매가격   수량   할인율   평점
0   B001  김민준    소설  한빛  서울  18000.0  2.0  10.0  4.3
1   B002  이서연  자기계발  길벗  부산  15000.0  3.0   0.0  3.9
2   B003  박지호    소설  한빛  서울  22000.0  1.0  15.0  NaN
3   B004  최수아    과학  을유  대전  19000.0  4.0   0.0  4.5
4   B005  정우진  자기계발  길벗  서울  13000.0  2.0   5.0  4.1
5   B006  강하은    소설  을유  부산  25000.0  1.0  20.0  NaN
6   B007  윤도현    과학  한빛  대전  17000.0  3.0   0.0  3.7
7   B008  임지유   NaN  길벗  서울  21000.0  2.0  10.0  4.6
8   B009  한준서  자기계발  을유  부산  14000.0  5.0   5.0  4.0
9   B010  오서현    소설  한빛  대전  23000.0  1.0  15.0  4.2
10  B011  배준혁    과학  길벗  서울  16000.0  4.0   0.0  3.8
11  B012  신하은  자기계발  을유  부산  18000.0  2.0   NaN  4.4
12  B013  류지원   NaN  한빛  서울  20000.0  3.0  10.0  NaN
13  B014  문서준    소설  길벗  대전      NaN  NaN   0.0  4.7
14  B015  남다인    과학  을유  부산  15000.0  2.0  20.0  3.9
15  B016  황지민  자기계발  한빛  서울  24000.0  1.0   5.0  4.1
16  B017  조현우    소설  길벗  대전  19000.0  3.0   NaN  4.3
17  B018  송미래    과학  을유  부산  16000.0  NaN  10.0  NaN
18  B019  전도윤   NaN  한빛  서울  22000.0  2.0   0.0  4.5
19  B020  백서진  자기계발  길벗  대전      NaN  4.0  15.0  4.0

---
### 문제 2.
컬럼별 결측치의 개수를 파악하여 결측치의 개수가 가장 많은 컬럼명을 변수 **'답_02'** 에 저장하고 출력하세요.  
ex> 답_02 = '컬럼1'  
ex> 답_02 = '컬럼1, 컬럼2'  (결측치 개수가 동일한 컬럼이 여러 개일 경우)

In [ ]:
# 문제 2번 풀이 작성
df.isnull().sum()
답_02 = '평점'
print(답_02)

'평점'

---
### 문제 3.
df 데이터를 아래 기준으로 결측치를 처리하세요. 처리된 결과는 **df에 저장**되어야 합니다.

1. `도서분류` 컬럼 → **'미분류'** 로 채우기
2. `할인율` 컬럼 → **0** 으로 채우기
3. `판매가격` 컬럼 → **평균값** 으로 채우기
4. `수량` 컬럼 → **중앙값** 으로 채우기
5. `평점` 컬럼 → **평균값** 으로 채우기 (소수점 둘째 자리)

In [6]:
# 문제 3번 풀이 작성
df['도서분류'] = df['도서분류'].fillna('미분류')
df['할인율'] = df['할인율'].fillna(0)
df['판매가격'] = df['판매가격'].fillna(df['판매가격'].mean())
df['수량'] = df['수량'].fillna(df['수량'].median())
df['평점'] = df['평점'].fillna(round(df['평점'].mean(), 2))

df

    주문번호  고객명  도서분류 출판사  지역          판매가격   수량   할인율    평점
0   B001  김민준    소설  한빛  서울  18000.000000  2.0  10.0  4.30
1   B002  이서연  자기계발  길벗  부산  15000.000000  3.0   0.0  3.90
2   B003  박지호    소설  한빛  서울  22000.000000  1.0  15.0  4.19
3   B004  최수아    과학  을유  대전  19000.000000  4.0   0.0  4.50
4   B005  정우진  자기계발  길벗  서울  13000.000000  2.0   5.0  4.10
5   B006  강하은    소설  을유  부산  25000.000000  1.0  20.0  4.19
6   B007  윤도현    과학  한빛  대전  17000.000000  3.0   0.0  3.70
7   B008  임지유   미분류  길벗  서울  21000.000000  2.0  10.0  4.60
8   B009  한준서  자기계발  을유  부산  14000.000000  5.0   5.0  4.00
9   B010  오서현    소설  한빛  대전  23000.000000  1.0  15.0  4.20
10  B011  배준혁    과학  길벗  서울  16000.000000  4.0   0.0  3.80
11  B012  신하은  자기계발  을유  부산  18000.000000  2.0   0.0  4.40
12  B013  류지원   미분류  한빛  서울  20000.000000  3.0  10.0  4.19
13  B014  문서준    소설  길벗  대전  18722.222222  2.0   0.0  4.70
14  B015  남다인    과학  을유  부산  15000.000000  2.0  20.0  3.90
15  B016  황지민  자기계발  한빛  서울  24000.000000  1.0   5.0  4.10
16  B017  조현우    소설  길벗  대전  19000.000000  3.0   0.0  4.30
17  B018  송미래    과학  을유  부산  16000.000000  2.0  10.0  4.19
18  B019  전도윤   미분류  한빛  서울  22000.000000  2.0   0.0  4.50
19  B020  백서진  자기계발  길벗  대전  18722.222222  4.0  15.0  4.00

---
### 문제 4.
df 에서 **'도서분류'** 와 **'출판사'** 컬럼만 선택하여 출력하세요.

In [7]:
# 문제 4번 풀이 작성
df[['도서분류', '출판사']]

    도서분류 출판사
0     소설  한빛
1   자기계발  길벗
2     소설  한빛
3     과학  을유
4   자기계발  길벗
5     소설  을유
6     과학  한빛
7    미분류  길벗
8   자기계발  을유
9     소설  한빛
10    과학  길벗
11  자기계발  을유
12   미분류  한빛
13    소설  길벗
14    과학  을유
15  자기계발  한빛
16    소설  길벗
17    과학  을유
18   미분류  한빛
19  자기계발  길벗

---
### 문제 5.
df 에서 지역이 **'서울'** 이거나 **'부산'** 인 주문 중 평점이 **4.0 이상** 인 주문 정보를 출력하세요.

In [8]:
# 문제 5번 풀이 작성
df[(df['지역'].isin(['서울', '부산'])) & (df['평점'] >= 4.0)]

    주문번호  고객명  도서분류 출판사  지역     판매가격   수량   할인율    평점
0   B001  김민준    소설  한빛  서울  18000.0  2.0  10.0  4.30
2   B003  박지호    소설  한빛  서울  22000.0  1.0  15.0  4.19
4   B005  정우진  자기계발  길벗  서울  13000.0  2.0   5.0  4.10
5   B006  강하은    소설  을유  부산  25000.0  1.0  20.0  4.19
7   B008  임지유   미분류  길벗  서울  21000.0  2.0  10.0  4.60
8   B009  한준서  자기계발  을유  부산  14000.0  5.0   5.0  4.00
11  B012  신하은  자기계발  을유  부산  18000.0  2.0   0.0  4.40
12  B013  류지원   미분류  한빛  서울  20000.0  3.0  10.0  4.19
15  B016  황지민  자기계발  한빛  서울  24000.0  1.0   5.0  4.10
17  B018  송미래    과학  을유  부산  16000.0  2.0  10.0  4.19
18  B019  전도윤   미분류  한빛  서울  22000.0  2.0   0.0  4.50

---
### 문제 6.
df 데이터를 아래 요구사항에 맞게 변경하세요.

1. `판매가격` 과 `수량` 을 곱한 **'총판매액'** 컬럼을 추가하세요.
2. `지역` 컬럼에서 **'대전'** 을 **'대전광역시'** 로 변경하세요.

In [9]:
# 문제 6번 풀이 작성
df['총판매액'] = df['판매가격']*df['수량']
df['지역'] = df['지역'].replace({'대전' : '대전광역시'})
df

    주문번호  고객명  도서분류 출판사     지역          판매가격   수량   할인율    평점          총판매액
0   B001  김민준    소설  한빛     서울  18000.000000  2.0  10.0  4.30  36000.000000
1   B002  이서연  자기계발  길벗     부산  15000.000000  3.0   0.0  3.90  45000.000000
2   B003  박지호    소설  한빛     서울  22000.000000  1.0  15.0  4.19  22000.000000
3   B004  최수아    과학  을유  대전광역시  19000.000000  4.0   0.0  4.50  76000.000000
4   B005  정우진  자기계발  길벗     서울  13000.000000  2.0   5.0  4.10  26000.000000
5   B006  강하은    소설  을유     부산  25000.000000  1.0  20.0  4.19  25000.000000
6   B007  윤도현    과학  한빛  대전광역시  17000.000000  3.0   0.0  3.70  51000.000000
7   B008  임지유   미분류  길벗     서울  21000.000000  2.0  10.0  4.60  42000.000000
8   B009  한준서  자기계발  을유     부산  14000.000000  5.0   5.0  4.00  70000.000000
9   B010  오서현    소설  한빛  대전광역시  23000.000000  1.0  15.0  4.20  23000.000000
10  B011  배준혁    과학  길벗     서울  16000.000000  4.0   0.0  3.80  64000.000000
11  B012  신하은  자기계발  을유     부산  18000.000000  2.0   0.0  4.40  36000.000000
12  B013  류지원   미분류  한빛     서울  20000.000000  3.0  10.0  4.19  60000.000000
13  B014  문서준    소설  길벗  대전광역시  18722.222222  2.0   0.0  4.70  37444.444444
14  B015  남다인    과학  을유     부산  15000.000000  2.0  20.0  3.90  30000.000000
15  B016  황지민  자기계발  한빛     서울  24000.000000  1.0   5.0  4.10  24000.000000
16  B017  조현우    소설  길벗  대전광역시  19000.000000  3.0   0.0  4.30  57000.000000
17  B018  송미래    과학  을유     부산  16000.000000  2.0  10.0  4.19  32000.000000
18  B019  전도윤   미분류  한빛     서울  22000.000000  2.0   0.0  4.50  44000.000000
19  B020  백서진  자기계발  길벗  대전광역시  18722.222222  4.0  15.0  4.00  74888.888889

---
### 문제 7.
df 데이터에서 **도서분류별 판매가격의 합계** 를 출력하세요.

In [10]:
# 문제 7번 풀이 작성
df.groupby('도서분류')['판매가격'].sum()

도서분류
과학       83000.000000
미분류      63000.000000
소설      125722.222222
자기계발    102722.222222
Name: 판매가격, dtype: float64

---
### 문제 8.
df 데이터에서 **판매가격 기준 내림차순** 으로 정렬하고, **상위 5개 주문** 의 고객명과 판매가격을 출력하세요.

In [11]:
# 문제 8번 풀이 작성
df.sort_values('판매가격', ascending=False).head(5)[['고객명', '판매가격']]

    고객명     판매가격
5   강하은  25000.0
15  황지민  24000.0
9   오서현  23000.0
2   박지호  22000.0
18  전도윤  22000.0

---
### 문제 9. ⭐ (심화)
df 데이터에서 아래 조건을 순서대로 처리하여 결과를 출력하세요.

1. `할인율` 이 **10 이상** 인 데이터만 필터링하세요.
2. 필터링된 데이터에서 **지역별, 도서분류별** 로 그룹핑하여 **판매가격의 평균** 을 구하세요.
3. 평균 판매가격 기준 **내림차순** 으로 정렬하세요.
4. 결과의 **인덱스를 초기화** 하여 출력하세요.

In [11]:
# 문제 9번 풀이 작성
# 1.
df[df['할인율'] >= 10]

# 2.
df[df['할인율'] >= 10].groupby(['지역', '도서분류'])['판매가격'].agg(['mean'])

# 3.
df[df['할인율'] >= 10].groupby(['지역', '도서분류'])['판매가격'].agg(['mean']).sort_values('mean', ascending=False)

# 4.
df[df['할인율'] >= 10].groupby(['지역', '도서분류'])['판매가격'].agg(['mean']).sort_values('mean', ascending=False).reset_index()

      지역  도서분류          mean
0     부산    소설  25000.000000
1  대전광역시    소설  23000.000000
2     서울   미분류  20500.000000
3     서울    소설  20000.000000
4  대전광역시  자기계발  18722.222222
5     부산    과학  15500.000000

---
### 문제 10. ⭐ (심화)
df 데이터를 활용하여 아래 조건을 모두 만족하는 결과를 만들고 **엑셀 파일로 저장** 하세요.

1. **'총판매액'** 컬럼을 추가하세요. (`판매가격` × `수량`)
2. **출판사별** 로 총판매액의 합계를 구하고 컬럼명을 **'출판사별_합계'** 로 변경하세요.
3. **출판사별_합계 기준 내림차순** 으로 정렬하고 인덱스를 초기화하세요.
4. 합계가 가장 높은 출판사에는 **'★ 1위'**, 나머지는 **'　'** 를 값으로 갖는 **'비고'** 컬럼을 추가하세요.
5. 완성된 데이터를 **'출판사별_판매분석.xlsx'** 파일로 저장하세요. (인덱스 저장 안 함)

In [12]:
# 문제 10번 풀이 작성
df1 = df.groupby('출판사')['총판매액'].agg(['sum']).rename(columns={'sum' : '출판사별_합계'}).sort_values('출판사별_합계', ascending=False).reset_index()

df1['비고'] = ''
df1['비고'] = df1['비고'].mask(df1['출판사별_합계'] == max(df1['출판사별_합계']), '★ 1위')

df1.to_excel('출판사별_판매분석.xlsx', index=False)